path.config=C:/users/egoru/OneDrive/Рабочий стол/launcher/src/main/resources/config.json
 #C:/ProgramData/Launcher/config/config.json
path.logs=C:/users/egoru/OneDrive/Рабочий стол/launcher/src/main/resources/logs
#C:/ProgramData/Launcher/logs/
log.level=INFO